/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainLayoutImport } from './routes/_mainLayout'
import { Route as IntradayIndexImport } from './routes/intraday/index'
import { Route as MainLayoutIndexImport } from './routes/_mainLayout.index'
import { Route as MainLayoutResultsImport } from './routes/_mainLayout.results'
import { Route as IntradayMarktanalyseIndexImport } from './routes/intraday/marktanalyse/index'
import { Route as IntradayMarktanalyseVorgehensweiseImTradingIndexImport } from './routes/intraday/marktanalyse/vorgehensweise-im-trading/index'

// Create/Update Routes

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRoute,
} as any)

const IntradayIndexRoute = IntradayIndexImport.update({
  id: '/intraday/',
  path: '/intraday/',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutIndexRoute = MainLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutResultsRoute = MainLayoutResultsImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => MainLayoutRoute,
} as any)

const IntradayMarktanalyseIndexRoute = IntradayMarktanalyseIndexImport.update({
  id: '/intraday/marktanalyse/',
  path: '/intraday/marktanalyse/',
  getParentRoute: () => rootRoute,
} as any)

const IntradayMarktanalyseVorgehensweiseImTradingIndexRoute =
  IntradayMarktanalyseVorgehensweiseImTradingIndexImport.update({
    id: '/intraday/marktanalyse/vorgehensweise-im-trading/',
    path: '/intraday/marktanalyse/vorgehensweise-im-trading/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout/results': {
      id: '/_mainLayout/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof MainLayoutResultsImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/intraday/': {
      id: '/intraday/'
      path: '/intraday'
      fullPath: '/intraday'
      preLoaderRoute: typeof IntradayIndexImport
      parentRoute: typeof rootRoute
    }
    '/intraday/marktanalyse/': {
      id: '/intraday/marktanalyse/'
      path: '/intraday/marktanalyse'
      fullPath: '/intraday/marktanalyse'
      preLoaderRoute: typeof IntradayMarktanalyseIndexImport
      parentRoute: typeof rootRoute
    }
    '/intraday/marktanalyse/vorgehensweise-im-trading/': {
      id: '/intraday/marktanalyse/vorgehensweise-im-trading/'
      path: '/intraday/marktanalyse/vorgehensweise-im-trading'
      fullPath: '/intraday/marktanalyse/vorgehensweise-im-trading'
      preLoaderRoute: typeof IntradayMarktanalyseVorgehensweiseImTradingIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface MainLayoutRouteChildren {
  MainLayoutResultsRoute: typeof MainLayoutResultsRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutResultsRoute: MainLayoutResultsRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof MainLayoutRouteWithChildren
  '/results': typeof MainLayoutResultsRoute
  '/': typeof MainLayoutIndexRoute
  '/intraday': typeof IntradayIndexRoute
  '/intraday/marktanalyse': typeof IntradayMarktanalyseIndexRoute
  '/intraday/marktanalyse/vorgehensweise-im-trading': typeof IntradayMarktanalyseVorgehensweiseImTradingIndexRoute
}

export interface FileRoutesByTo {
  '/results': typeof MainLayoutResultsRoute
  '/': typeof MainLayoutIndexRoute
  '/intraday': typeof IntradayIndexRoute
  '/intraday/marktanalyse': typeof IntradayMarktanalyseIndexRoute
  '/intraday/marktanalyse/vorgehensweise-im-trading': typeof IntradayMarktanalyseVorgehensweiseImTradingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/_mainLayout/results': typeof MainLayoutResultsRoute
  '/_mainLayout/': typeof MainLayoutIndexRoute
  '/intraday/': typeof IntradayIndexRoute
  '/intraday/marktanalyse/': typeof IntradayMarktanalyseIndexRoute
  '/intraday/marktanalyse/vorgehensweise-im-trading/': typeof IntradayMarktanalyseVorgehensweiseImTradingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/results'
    | '/'
    | '/intraday'
    | '/intraday/marktanalyse'
    | '/intraday/marktanalyse/vorgehensweise-im-trading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/results'
    | '/'
    | '/intraday'
    | '/intraday/marktanalyse'
    | '/intraday/marktanalyse/vorgehensweise-im-trading'
  id:
    | '__root__'
    | '/_mainLayout'
    | '/_mainLayout/results'
    | '/_mainLayout/'
    | '/intraday/'
    | '/intraday/marktanalyse/'
    | '/intraday/marktanalyse/vorgehensweise-im-trading/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  IntradayIndexRoute: typeof IntradayIndexRoute
  IntradayMarktanalyseIndexRoute: typeof IntradayMarktanalyseIndexRoute
  IntradayMarktanalyseVorgehensweiseImTradingIndexRoute: typeof IntradayMarktanalyseVorgehensweiseImTradingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
  IntradayIndexRoute: IntradayIndexRoute,
  IntradayMarktanalyseIndexRoute: IntradayMarktanalyseIndexRoute,
  IntradayMarktanalyseVorgehensweiseImTradingIndexRoute:
    IntradayMarktanalyseVorgehensweiseImTradingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_mainLayout",
        "/intraday/",
        "/intraday/marktanalyse/",
        "/intraday/marktanalyse/vorgehensweise-im-trading/"
      ]
    },
    "/_mainLayout": {
      "filePath": "_mainLayout.tsx",
      "children": [
        "/_mainLayout/results",
        "/_mainLayout/"
      ]
    },
    "/_mainLayout/results": {
      "filePath": "_mainLayout.results.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/": {
      "filePath": "_mainLayout.index.tsx",
      "parent": "/_mainLayout"
    },
    "/intraday/": {
      "filePath": "intraday/index.tsx"
    },
    "/intraday/marktanalyse/": {
      "filePath": "intraday/marktanalyse/index.tsx"
    },
    "/intraday/marktanalyse/vorgehensweise-im-trading/": {
      "filePath": "intraday/marktanalyse/vorgehensweise-im-trading/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
